nelmio_api_doc:
    documentation:
        info:
            title: TalkToTalk
            description: This is an awesome app!
            version: 1.0.0
    use_validation_groups: true
    areas: # to filter documented areas
        path_patterns:
            - ^/[a-z]
